GET http://localhost:8080/student/find?id=1

###
POST http://localhost:8080/student
Content-Type: application/json

{
  "id": "88",
  "name": "testStudent",
  "age": "24"
}

###
GET http://localhost:8080/student/19/faculty

###
DELETE http://localhost:8080/student/88