GET http://localhost:8080/student/find?id=1

###
POST http://localhost:8080/student
Content-Type: application/json

{
  "id": 8,
  "name": "testStudent",
  "age": 24
}

###
GET http://localhost:8080/student/1/faculty

###
DELETE http://localhost:8080/student/8

###
GET http://localhost:8080/student/count

###
GET http://localhost:8080/student/averageAge

###
GET http://localhost:8080/student/lastStudents?number=3